parameters:
    redmonster_paul_revere.announcement_repository.class: Redmonster\PaulRevereBundle\Entity\AnnouncementRepository
    redmonster_paul_revere.entity.announcement: Redmonster\PaulRevereBundle\Entity\Announcement

services:
    redmonster_paul_revere.repository.announcement:
        factory_service: "doctrine.orm.entity_manager"
        factory_method: "getRepository"
        class: "%redmonster_paul_revere.announcement_repository.class%"
        arguments:
            -  "%redmonster_paul_revere.entity.announcement%"

