parameters:
    redmonster_announcement.announcement_repository.class: Redmonster\AnnouncementBundle\Entity\AnnouncementRepository
    redmonster_announcement.entity.announcement: Redmonster\AnnouncementBundle\Entity\Announcement

services:
    redmonster_announcement.repository.announcement:
        factory_service: "doctrine.orm.entity_manager"
        factory_method: "getRepository"
        class: "%redmonster_announcement.announcement_repository.class%"
        arguments:
            -  "%redmonster_announcement.entity.announcement%"

